version: '3.8'


services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env

  djangoq:
    build: .
    volumes:
        - ./:/app
    ports:
        - "8002:8002"
    command: python manage.py qcluster
    depends_on:
        - app        

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
    db:
    static:      