version: '3.8'


services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn DjangoBoilerplate.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    env_file:
      - ./.env.prod.db  

volumes:
  postgres_data: