version: '3.8'


services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  djangoq:
      build: .
      command: python manage.py qcluster
      volumes:
          - ./:/django-app
      env_file:
          - ./.env.dev    
      depends_on:
          - web    
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: